insert into wunschliste values (1,"Holz und HWS","Ein Holz-Kopft allein reicht einfach nicht...",600,0,0,"holz1.jpg");
insert into wunschliste values (2,"Beschläge","Dass alles sitzt und bleibt wo es sein soll",400,0,0,"beschlaegebett.jpg");
insert into wunschliste values (3,"Glas","Lichteffekte durch Milchglas verwöhnen die Augen",200,0,0,"glas1.jpg");
insert into wunschliste values (4,"Licht und Extras","Leselampen gehören für uns einfach dazu",300,0,0,"lampe.jpg");
insert into wunschliste values (5,"Matrazen","Die Dynamik der Beziehung fördern...",1000,0,0,"matraze.jpg");
insert into wunschliste values (6,"Lättlirost","Kräftig und Ausdauernd",300,0,0,"lattenrost.jpg");
insert into wunschliste values (7,"Duvet","Das umkämpfte Bettobjekt...",600,0,0,"duvet.jpg");
insert into wunschliste values (8,"Kissen","Kopfauflage für Matthias, zum Wegschieben für Debi",300,0,0,"kissen.jpg");
insert into wunschliste values (9,"Duvet Bezüge","Einpackungsstoff",200,0,0,"duvetbezug.jpg");
insert into wunschliste values (10,"Fixleintücher","Zum Schutz der Matraze",160,0,0,"fixleintuch.jpg");
insert into wunschliste values (11,"Holz","Ein Schrank aus Holz ist heimelig",400,0,1,"holz2.jpg");
insert into wunschliste values (12,"Beschläge","Diese Schubladenauszüge müssen einiges aushalten...",1600,0,1,"beschlaegeschrank.jpg");
insert into wunschliste values (13,"Spiegel","Für den WOW-Effekt",200,0,1,"spiegel1.jpg");
insert into wunschliste values (14,"Glas","Lichteffekte durch Milchglas verwöhnen die Augen",100,0,1,"glas2.jpg");
insert into wunschliste values (15,"2x Flug nach Montenegro und zurück :)","Abheben ohne abzuheben",1000,0,2,"flugzeug.jpg");
insert into wunschliste values (16,"4 Übernachtungen am Strand","4 Tage geniessen und entspannen am Meer",1000,0,2,"strand.jpg");
insert into wunschliste values (17,"chic essen gehen","Unsere Ehe angemessen feiern",300,0,2,"chic.jpg");
insert into wunschliste values (18,"Details geniessen","Ein Glacé; zwischendurch...",100,0,2,"geniessen.jpg");
insert into wunschliste values (19,"4 Tage unterwegs","Bei Freunden in Podgorica...",400,0,2,"podgorica.jpg");
insert into wunschliste values (20,"Schubladenturm für Besteck","Irgendwo muss das Besteck hin, wenn der Geschirrspühler kommt",200,0,3,"schubladenschrank.jpg");
insert into wunschliste values (21,"Geschirrspüler","Dass wir die Zeit für anderes brauchen können...",2500,2500,3,"geschirrspueler.jpg");
insert into wunschliste values (22,"Ikea Einkauf","Schnickschnack für Debi...",200,0,3,"ikea.jpg");
insert into wunschliste values (23,"Spiegel Badezimmer","Dass alles etwas grösser wirkt.",100,0,3,"spiegel2.jpg");
insert into wunschliste values (24,"Frottee-Wäsche","Abtrocknen macht Spass",200,0,3,"frottee.jpg");
insert into wunschliste values (25,"Zimmerpflanzen","Nicht, dass es wieder verdorrt",150,0,3,"pflanze.jpg");
insert into wunschliste values (26,"Gesellschaftsspiel für 2","Zeit zu zweit geniessen",1,0,4,"spiel1.jpg");
insert into wunschliste values (27,"anderes Gesellschaftsspiel für 2","Zeit zu zweit anders geniessen",1,0,4,"spiel2.jpg");
insert into wunschliste values (28,"Gesellschaftsspiel für 4-8","Wenn Freunde da sind. Bitte kein DOG.",1,0,4,"spiel3.jpg");
insert into wunschliste values (29,"CD Joss Stone","Jazz und Soul für ins Wohnzimmer",1,0,4,"jossstone.jpg");